name: JereTile
description: Ring my Tile devices

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cryptography: ^2.7.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.4

flutter:
  uses-material-design: true
